import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url().optional(),
    PAYMENT_PROVIDER: z.enum(["bog", "tbc"]).optional(),
    PAYMENT_CLIENT_ID: z.string().optional(),
    PAYMENT_SECRET: z.string().optional(),
    PAYMENT_WEBHOOK_SECRET: z.string().optional(),
    QSTASH_TOKEN: z.string().optional(),
    QSTASH_SIGNING_KEY: z.string().optional(),
    REDIS_URL: z.string().optional(),
    WHATSAPP_TOKEN: z.string().optional(),
    WHATSAPP_PHONE_ID: z.string().optional(),
    TELEGRAM_BOT_TOKEN: z.string().optional(),
    TELEGRAM_ALERT_CHANNEL: z.string().optional(),
    RESEND_API_KEY: z.string().optional(),
    WEATHER_API_KEY: z.string().optional(),
    R2_ACCOUNT_ID: z.string().optional(),
    R2_ACCESS_KEY_ID: z.string().optional(),
    R2_SECRET_ACCESS_KEY: z.string().optional(),
    R2_BUCKET: z.string().optional(),
    PAYLOAD_SECRET: z.string().optional(),
    ADMIN_ALLOWED_EMAILS: z.string().optional(),
    INDEXNOW_KEY: z.string().optional(),
  },
  client: {
    NEXT_PUBLIC_SITE_URL: z.string().url().default("http://localhost:3000"),
    NEXT_PUBLIC_MAPTILER_KEY: z.string().optional(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    PAYMENT_PROVIDER: process.env.PAYMENT_PROVIDER,
    PAYMENT_CLIENT_ID: process.env.PAYMENT_CLIENT_ID,
    PAYMENT_SECRET: process.env.PAYMENT_SECRET,
    PAYMENT_WEBHOOK_SECRET: process.env.PAYMENT_WEBHOOK_SECRET,
    QSTASH_TOKEN: process.env.QSTASH_TOKEN,
    QSTASH_SIGNING_KEY: process.env.QSTASH_SIGNING_KEY,
    REDIS_URL: process.env.REDIS_URL,
    WHATSAPP_TOKEN: process.env.WHATSAPP_TOKEN,
    WHATSAPP_PHONE_ID: process.env.WHATSAPP_PHONE_ID,
    TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
    TELEGRAM_ALERT_CHANNEL: process.env.TELEGRAM_ALERT_CHANNEL,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    WEATHER_API_KEY: process.env.WEATHER_API_KEY,
    R2_ACCOUNT_ID: process.env.R2_ACCOUNT_ID,
    R2_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID,
    R2_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY,
    R2_BUCKET: process.env.R2_BUCKET,
    PAYLOAD_SECRET: process.env.PAYLOAD_SECRET,
    ADMIN_ALLOWED_EMAILS: process.env.ADMIN_ALLOWED_EMAILS,
    INDEXNOW_KEY: process.env.INDEXNOW_KEY,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    NEXT_PUBLIC_MAPTILER_KEY: process.env.NEXT_PUBLIC_MAPTILER_KEY,
  },
  emptyStringAsUndefined: true,
  skipValidation: process.env.SKIP_ENV_VALIDATION === "true",
});
