import type { Place } from "./types";

export const places: Place[] = [
  {
    slug: "gudauri-paragliding",
    resort: "gudauri",
    category: "paragliding",
    name: { en: "Gudauri Paragliding", ru: "Гудаури Парапланеризм", ka: "გუდაური პარაპლანერიზმი" },
    description: {
      en: "Tandem flights off the ridge above the New Gudauri hotel cluster. Ten-minute flight down to the base, on-mountain photographer included.",
      ru: "Тандемные полёты с гребня над кластером «Новый Гудаури». Десятиминутный спуск к базе, горный фотограф в комплекте.",
      ka: "ტანდემი ფრენები ახალი გუდაურის სასტუმროების ზემოთ. ათწუთიანი ფრენა ბაზამდე, ფოტოგრაფი კომპლექტში.",
    },
    priceFromGel: 250,
    hours: { en: "10:00–15:00 (weather-dependent)", ru: "10:00–15:00 (по погоде)", ka: "10:00–15:00 (ამინდის მიხედვით)" },
    phone: "+995 555 100 200",
    tags: ["English spoken", "Card accepted"],
  },
  {
    slug: "gudauri-cozy-corner",
    resort: "gudauri",
    category: "restaurant",
    name: { en: "Cozy Corner", ru: "Уютный уголок", ka: "მყუდრო კუთხე" },
    description: {
      en: "Small Georgian kitchen next to the base area. Fresh khinkali cooked to order, hot wine, no queue after 20:00.",
      ru: "Маленькая грузинская кухня у нижней станции. Хинкали лепят под заказ, глинтвейн, после 20:00 очереди нет.",
      ka: "პატარა ქართული სამზარეულო ძირის სადგურთან. ხინკალი შეკვეთით, ცხელი ღვინო, 20:00-ის შემდეგ რიგი არაა.",
    },
    priceFromGel: 30,
    hours: { en: "12:00–23:00 daily", ru: "12:00–23:00 ежедневно", ka: "12:00–23:00 ყოველდღე" },
    phone: "+995 555 100 210",
    tags: ["Family friendly", "Card accepted"],
  },
  {
    slug: "gudauri-black-bar",
    resort: "gudauri",
    category: "bar",
    name: { en: "Black Bar Après", ru: "Black Bar Апре", ka: "Black Bar Après" },
    description: {
      en: "The default après-ski. DJ from 18:00 in season, hot Rkatsiteli, a short window with actual snow on the deck.",
      ru: "Афтерсноу по умолчанию. Диджей с 18:00 в сезон, горячее ркацители, короткое окно с настоящим снегом на террасе.",
      ka: "სტანდარტული après-ski. DJ 18:00-დან სეზონში, ცხელი რქაწითელი, მოკლე ფანჯარა რეალური თოვლით ტერასაზე.",
    },
    priceFromGel: 15,
    hours: { en: "16:00–02:00", ru: "16:00–02:00", ka: "16:00–02:00" },
    phone: "+995 555 100 220",
    tags: ["English spoken", "Card accepted"],
  },
  {
    slug: "gudauri-rent-and-ride",
    resort: "gudauri",
    category: "rental",
    name: { en: "Rent & Ride Gudauri", ru: "Rent & Ride Гудаури", ka: "Rent & Ride გუდაური" },
    description: {
      en: "Full ski and snowboard rental at the base. Book online for the season and a set is waiting the morning you arrive.",
      ru: "Полный прокат лыж и сноубордов у базы. Забронируйте на сезон онлайн — комплект ждёт вас с утра.",
      ka: "სრული თხილამურის და სნოუბორდის ქირავნობა ძირში. დაჯავშნეთ ონლაინ სეზონისთვის — კომპლექტი დილიდან გელოდებათ.",
    },
    priceFromGel: 45,
    hours: { en: "08:30–19:00", ru: "08:30–19:00", ka: "08:30–19:00" },
    phone: "+995 555 100 230",
    tags: ["English spoken", "Card accepted"],
    bookingUrl: "https://example.com/book/rent-and-ride",
  },
  {
    slug: "bakuriani-tubing-park",
    resort: "bakuriani",
    category: "tubing",
    name: { en: "Bakuriani Tubing Park", ru: "Тюбинг-парк Бакуриани", ka: "ბაკურიანის ტუბინგ-პარკი" },
    description: {
      en: "Long lit tubing track just behind Didveli base. Popular for the last hour of light and evenings under floodlights.",
      ru: "Длинная освещённая трасса тюбинга сразу за базой Дидвели. Популярна на закате и вечером с прожекторами.",
      ka: "გრძელი განათებული ტუბინგის ტრასა დიდველის ძირის უკან. პოპულარულია მზის ჩასვლის და საღამოს პროჟექტორების ქვეშ.",
    },
    priceFromGel: 20,
    hours: { en: "11:00–22:00 in season", ru: "11:00–22:00 в сезон", ka: "11:00–22:00 სეზონში" },
    phone: "+995 555 200 100",
    tags: ["Family friendly", "Card accepted"],
  },
  {
    slug: "bakuriani-ski-school-alpina",
    resort: "bakuriani",
    category: "ski-school",
    name: { en: "Alpina Ski School", ru: "Горнолыжная школа Alpina", ka: "სასწავლო სკოლა Alpina" },
    description: {
      en: "Certified instructors, English and Russian speaking. Kids-only morning groups; adult private in the afternoon.",
      ru: "Сертифицированные инструкторы, английский и русский. Утром — детские группы; днём — частные уроки для взрослых.",
      ka: "სერტიფიცირებული ინსტრუქტორები, ინგლისურად და რუსულად. დილით — ბავშვთა ჯგუფები; დღის ბოლოს — ინდივიდუალური მოზრდილთათვის.",
    },
    priceFromGel: 80,
    hours: { en: "09:00–17:00", ru: "09:00–17:00", ka: "09:00–17:00" },
    phone: "+995 555 200 110",
    tags: ["English spoken", "Family friendly"],
    bookingUrl: "https://example.com/book/alpina",
  },
  {
    slug: "mestia-cafe-laila",
    resort: "tetnuldi",
    category: "restaurant",
    name: { en: "Café Laila", ru: "Café Laila", ka: "Café Laila" },
    description: {
      en: "The Mestia central square standard: kubdari, tashmijabi, live Svan polyphony most nights in season.",
      ru: "Классика центральной площади Местии: кубдари, ташмиджаби, живое сванское многоголосие большинством вечеров.",
      ka: "მესტიის ცენტრალური მოედნის სტანდარტი: კუბდარი, ტაშმიჯაბი, ცოცხალი სვანური მრავალხმიანობა სეზონში საღამოებში.",
    },
    priceFromGel: 40,
    hours: { en: "10:00–00:00", ru: "10:00–00:00", ka: "10:00–00:00" },
    phone: "+995 555 300 100",
    tags: ["English spoken", "Card accepted"],
  },
  {
    slug: "kazbegi-freeride-guides",
    resort: "kazbegi",
    category: "heliski",
    name: { en: "Kazbegi Freeride & Guides", ru: "Казбеги Фрирайд и Гиды", ka: "ყაზბეგი ფრირაიდი და გიდები" },
    description: {
      en: "Certified UIAGM guides for ski-touring, freeride days and helicopter drops on the Gergeti glacier system. Booking a guide is mandatory here.",
      ru: "Сертифицированные UIAGM гиды для ски-тура, фрирайд-дней и вертолётных высадок на леднике Гергети. Здесь гид обязателен.",
      ka: "UIAGM სერტიფიცირებული გიდები ski-touring-ისთვის, ფრირაიდ დღეებისთვის და გერგეტის მყინვარზე ვერტმფრენით მისვლისთვის. აქ გიდის დაქირავება სავალდებულოა.",
    },
    priceFromGel: 400,
    hours: { en: "By appointment", ru: "По записи", ka: "შეხვედრით" },
    phone: "+995 555 400 100",
    tags: ["English spoken", "Guide required"],
  },
];
