import type { Route } from "./types";

export const routes: Route[] = [
  {
    slug: "tbilisi-airport-gudauri",
    from: { en: "Tbilisi Airport (TBS)", ru: "Аэропорт Тбилиси (TBS)", ka: "თბილისის აეროპორტი (TBS)" },
    fromSlug: "tbilisi-airport",
    to: { en: "Gudauri", ru: "Гудаури", ka: "გუდაური" },
    toSlug: "gudauri",
    toResort: "gudauri",
    region: "from-airports",
    distanceKm: 140,
    durationMin: 150,
    requires4x4: false,
    isScheduled: false,
    description: {
      en: "Airport-to-Gudauri is the single most-booked transfer of the season. Meet-and-greet at arrivals with a name sign, straight up the Georgian Military Road over the Jvari Pass. Winter tyres and chains on every vehicle; 4x4 available when the pass is limited.",
      ru: "Аэропорт — Гудаури: самый популярный трансфер сезона. Встреча в зоне прилёта с табличкой, дальше по Военно-Грузинской дороге через Крестовый перевал. Зимняя резина и цепи на каждой машине; при ограничениях на перевале доступен 4x4.",
      ka: "აეროპორტიდან გუდაურამდე — სეზონის ყველაზე ხშირად დაჯავშნილი ტრანსფერი. შეხვედრა ჩამოსვლის ზონაში სახელობითი ტაბლოთი, შემდეგ — საქართველოს სამხედრო გზა ჯვრის უღელტეხილზე. ზამთრის საბურავები და ჯაჭვები ყველა მანქანაზე; შეზღუდვისას 4x4 ხელმისაწვდომია.",
    },
    prices: {
      shared: { priceGel: 40, maxPax: 1 },
      sedan: { priceGel: 180, maxPax: 3 },
      minivan: { priceGel: 260, maxPax: 7 },
      suv4x4: { priceGel: 300, maxPax: 5 },
    },
  },
  {
    slug: "tbilisi-gudauri",
    from: { en: "Tbilisi (city)", ru: "Тбилиси (город)", ka: "თბილისი (ქალაქი)" },
    fromSlug: "tbilisi",
    to: { en: "Gudauri", ru: "Гудаури", ka: "გუდაური" },
    toSlug: "gudauri",
    toResort: "gudauri",
    region: "from-tbilisi",
    distanceKm: 120,
    durationMin: 135,
    requires4x4: false,
    isScheduled: false,
    description: {
      en: "Pickup from your Tbilisi hotel or apartment, straight to your Gudauri accommodation. Shared seats available on the morning run; whole-vehicle any time.",
      ru: "Забор из отеля или квартиры в Тбилиси, доставка прямо к жилью в Гудаури. Утром доступны шеринговые места; целая машина — в любое время.",
      ka: "აყვანა თბილისის სასტუმროდან ან ბინიდან, პირდაპირ გუდაურის საცხოვრებელამდე. დილით ხელმისაწვდომია გაზიარებული ადგილები; მთელი მანქანა — ნებისმიერ დროს.",
    },
    prices: {
      shared: { priceGel: 35, maxPax: 1 },
      sedan: { priceGel: 160, maxPax: 3 },
      minivan: { priceGel: 240, maxPax: 7 },
    },
  },
  {
    slug: "tbilisi-bakuriani",
    from: { en: "Tbilisi", ru: "Тбилиси", ka: "თბილისი" },
    fromSlug: "tbilisi",
    to: { en: "Bakuriani", ru: "Бакуриани", ka: "ბაკურიანი" },
    toSlug: "bakuriani",
    toResort: "bakuriani",
    region: "from-tbilisi",
    distanceKm: 180,
    durationMin: 195,
    requires4x4: false,
    isScheduled: false,
    description: {
      en: "Three hours south via Gori and the Borjomi gorge. A common combination: transfer to Bakuriani, ride the narrow-gauge train back to Borjomi as a day trip.",
      ru: "Три часа на юг через Гори и Боржомское ущелье. Частая связка: трансфер в Бакуриани, обратно на день — узкоколейкой в Боржоми.",
      ka: "სამი საათი სამხრეთით გორის და ბორჯომის ხეობის გავლით. ხშირი კომბინაცია: ტრანსფერი ბაკურიანში, ერთდღიური მოგზაურობა ვიწროლიანდაგიანი მატარებლით ბორჯომში.",
    },
    prices: {
      sedan: { priceGel: 220, maxPax: 3 },
      minivan: { priceGel: 320, maxPax: 7 },
    },
  },
  {
    slug: "tbilisi-kazbegi",
    from: { en: "Tbilisi", ru: "Тбилиси", ka: "თბილისი" },
    fromSlug: "tbilisi",
    to: { en: "Kazbegi (Stepantsminda)", ru: "Казбеги (Степанцминда)", ka: "ყაზბეგი (სტეფანწმინდა)" },
    toSlug: "kazbegi",
    toResort: "kazbegi",
    region: "from-tbilisi",
    distanceKm: 155,
    durationMin: 180,
    requires4x4: true,
    isScheduled: false,
    description: {
      en: "Over the Jvari Pass and 30 km further to Stepantsminda under Mount Kazbek. Winter: 4x4 recommended and often mandatory. Photo stops at Gudauri and the Russia-Georgia Friendship Monument by default.",
      ru: "Через Крестовый перевал и ещё 30 км до Степанцминды под Казбеком. Зимой: 4x4 рекомендуется, часто обязателен. По умолчанию фотоостановки в Гудаури и у Монумента дружбы.",
      ka: "ჯვრის უღელტეხილზე და კიდევ 30 კმ სტეფანწმინდამდე მყინვარწვერის ქვეშ. ზამთარში: 4x4 რეკომენდებული, ხშირად სავალდებულო. სტანდარტულად ფოტოგადაღების გაჩერებები გუდაურში და მეგობრობის მონუმენტთან.",
    },
    prices: {
      minivan: { priceGel: 300, maxPax: 7 },
      suv4x4: { priceGel: 350, maxPax: 5 },
    },
  },
  {
    slug: "gudauri-kazbegi",
    from: { en: "Gudauri", ru: "Гудаури", ka: "გუდაური" },
    fromSlug: "gudauri",
    to: { en: "Kazbegi", ru: "Казбеги", ka: "ყაზბეგი" },
    toSlug: "kazbegi",
    toResort: "kazbegi",
    region: "from-tbilisi",
    distanceKm: 35,
    durationMin: 40,
    requires4x4: true,
    isScheduled: false,
    description: {
      en: "The classic rest-day drive from Gudauri: 40 minutes north to Gergeti Trinity Church and the Kazbek panorama. 4x4 only in winter.",
      ru: "Классический день отдыха из Гудаури: 40 минут на север к храму Святой Троицы в Гергети и панораме Казбека. Зимой только 4x4.",
      ka: "კლასიკური დასვენების დღის მოგზაურობა გუდაურიდან: 40 წუთი ჩრდილოეთით გერგეტის სამების ეკლესიამდე და მყინვარწვერის პანორამამდე. ზამთარში მხოლოდ 4x4.",
    },
    prices: {
      suv4x4: { priceGel: 140, maxPax: 5 },
    },
  },
  {
    slug: "kutaisi-airport-mestia",
    from: { en: "Kutaisi Airport (KUT)", ru: "Аэропорт Кутаиси (KUT)", ka: "ქუთაისის აეროპორტი (KUT)" },
    fromSlug: "kutaisi-airport",
    to: { en: "Mestia", ru: "Местия", ka: "მესტია" },
    toSlug: "mestia",
    region: "from-airports",
    distanceKm: 240,
    durationMin: 330,
    requires4x4: false,
    isScheduled: false,
    description: {
      en: "Long haul: 5–6 hours through the Enguri gorge to Upper Svaneti. Best done in daylight for the road itself. Break at Zugdidi.",
      ru: "Длинный перегон: 5–6 часов через Ингурское ущелье в Верхнюю Сванетию. Лучше засветло — ради самой дороги. Остановка в Зугдиди.",
      ka: "გრძელი გზა: 5–6 საათი ენგურის ხეობით ზემო სვანეთამდე. ჯობია დღისით — თვითონ გზის გამო. გაჩერება ზუგდიდში.",
    },
    prices: {
      minivan: { priceGel: 450, maxPax: 7 },
    },
  },
  {
    slug: "zugdidi-mestia",
    from: { en: "Zugdidi", ru: "Зугдиди", ka: "ზუგდიდი" },
    fromSlug: "zugdidi",
    to: { en: "Mestia", ru: "Местия", ka: "მესტია" },
    toSlug: "mestia",
    region: "svaneti",
    distanceKm: 140,
    durationMin: 165,
    requires4x4: false,
    isScheduled: false,
    description: {
      en: "The last leg of the classic Tbilisi → Zugdidi (overnight train) → Mestia route. Three hours through the Enguri hydro reservoir and up.",
      ru: "Финальный участок классического маршрута Тбилиси → Зугдиди (ночной поезд) → Местия. Три часа через Ингурское водохранилище и вверх.",
      ka: "თბილისი → ზუგდიდი (ღამის მატარებელი) → მესტიის კლასიკური მარშრუტის ბოლო მონაკვეთი. სამი საათი ენგურის წყალსაცავზე გავლით და ზემოთ.",
    },
    prices: {
      minivan: { priceGel: 250, maxPax: 7 },
    },
  },
  {
    slug: "mestia-tetnuldi",
    from: { en: "Mestia", ru: "Местия", ka: "მესტია" },
    fromSlug: "mestia",
    to: { en: "Tetnuldi (base)", ru: "Тетнулди (база)", ka: "თეთნულდი (ძირი)" },
    toSlug: "tetnuldi",
    toResort: "tetnuldi",
    region: "svaneti",
    distanceKm: 15,
    durationMin: 50,
    requires4x4: true,
    isScheduled: true,
    schedule: [
      { departTime: "09:00", returnTime: "16:30", runsDaily: true },
    ],
    description: {
      en: "Daily scheduled shuttle. Morning departure from Mestia at 09:00, return at 16:30. Seats sold per day; buy the return-week bundle for the season pass.",
      ru: "Ежедневный шаттл. Отправление из Местии в 09:00, обратно в 16:30. Места продаются на день; для абонемента берите пакет на неделю.",
      ka: "ყოველდღიური შატლი. მესტიიდან 09:00-ზე გამგზავრება, უკან — 16:30-ზე. ადგილები ცალკე დღეზე იყიდება; კვირის აბონემენტისთვის კომბოს აიღეთ.",
    },
    prices: {
      shared: { priceGel: 30, maxPax: 1 },
      suv4x4: { priceGel: 150, maxPax: 5 },
    },
  },
  {
    slug: "mestia-hatsvali",
    from: { en: "Mestia", ru: "Местия", ka: "მესტია" },
    fromSlug: "mestia",
    to: { en: "Hatsvali", ru: "Хацвали", ka: "ჰაცვალი" },
    toSlug: "hatsvali",
    toResort: "hatsvali",
    region: "svaneti",
    distanceKm: 8,
    durationMin: 20,
    requires4x4: true,
    isScheduled: false,
    description: {
      en: "Short 4x4 hop to the smaller Mestia-side resort. Twenty minutes each way.",
      ru: "Короткий 4x4-переезд к малому курорту у Местии. Двадцать минут в одну сторону.",
      ka: "მოკლე 4x4 გადასვლა მესტიის მხრიდან პატარა კურორტამდე. ოცი წუთი ერთი მიმართულებით.",
    },
    prices: {
      suv4x4: { priceGel: 80, maxPax: 5 },
    },
  },
  {
    slug: "tbilisi-airport-batumi",
    from: { en: "Tbilisi Airport (TBS)", ru: "Аэропорт Тбилиси (TBS)", ka: "თბილისის აეროპორტი (TBS)" },
    fromSlug: "tbilisi-airport",
    to: { en: "Batumi", ru: "Батуми", ka: "ბათუმი" },
    toSlug: "batumi",
    region: "cross-country",
    distanceKm: 380,
    durationMin: 330,
    requires4x4: false,
    isScheduled: false,
    description: {
      en: "Coast-to-coast: 5–6 hours across Georgia on the E60 through Gori, Kutaisi and the Rioni valley to the Black Sea. Meet-and-greet at arrivals, one comfort stop, straight to your Batumi hotel or the Sea Towers.",
      ru: "От гор до моря: 5–6 часов через всю Грузию по трассе E60 — Гори, Кутаиси, долина Риони и на побережье Чёрного моря. Встреча в аэропорту, одна остановка на отдых, до вашего отеля в Батуми или башен на набережной.",
      ka: "მთიდან ზღვამდე: 5–6 საათი მთელი საქართველოს გავლით E60-ზე — გორი, ქუთაისი, რიონის ხეობა და შავი ზღვის სანაპირო. შეხვედრა აეროპორტში, ერთი დასვენების გაჩერება, პირდაპირ თქვენს სასტუმროსთან ან ბათუმის ცათამბჯენებთან.",
    },
    prices: {
      sedan: { priceGel: 380, maxPax: 3 },
      minivan: { priceGel: 520, maxPax: 7 },
    },
  },
  {
    slug: "batumi-goderdzi",
    from: { en: "Batumi", ru: "Батуми", ka: "ბათუმი" },
    fromSlug: "batumi",
    to: { en: "Goderdzi", ru: "Годердзи", ka: "გოდერძი" },
    toSlug: "goderdzi",
    toResort: "goderdzi",
    region: "adjara",
    distanceKm: 110,
    durationMin: 210,
    requires4x4: true,
    isScheduled: false,
    description: {
      en: "3–4 hours from Batumi. Winter road only for 4x4 with chains — pass the driver's kit check on the phone before you book. The reward is Georgia's snowiest resort.",
      ru: "3–4 часа из Батуми. Зимняя дорога только для 4x4 с цепями — сверьте комплект водителя по телефону до бронирования. Награда — самый снежный курорт Грузии.",
      ka: "3–4 საათი ბათუმიდან. ზამთრის გზა მხოლოდ 4x4-ისთვისაა ჯაჭვებით — დაჯავშნამდე ტელეფონით შეამოწმეთ მძღოლის აღჭურვილობა. ჯილდო — საქართველოს ყველაზე თოვლიანი კურორტი.",
    },
    prices: {
      suv4x4: { priceGel: 300, maxPax: 5 },
    },
  },
];

export function findRoute(slug: string) {
  return routes.find((r) => r.slug === slug);
}
